sudo: false

# version automatically picked up from .ruby-version
language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem install bundler jekyll

before_script:
  - chmod +x ./bin/setup
  - ./bin/setup
  - bundle exec jekyll build

script: bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --assume-extension --check-opengraph --url-ignore "feed.xml,/facebook.com/"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - LC_ALL=en_US.UTF-8
    - JEKYLL_ENV=production

