source "https://rubygems.org"

gem "autoprefixer-rails"
gem "html-proofer"
gem "image_optim"
gem "jekyll"
gem "jekyll-assets"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jemoji"
gem "mini_magick"
gem "sass"
gem "sprockets", "4.0.0.beta6"
gem "uglifier"
