exclude:
  - "vendor/*"

linters:
  StringQuotes:
    enabled: true
    style: double_quotes

  UrlFormat:
    enabled: false

  SelectorDepth:
    enabled: true
    max_depth: 4

  PropertySortOrder:
    enabled: true
    order: recess

  LeadingZero:
    enabled: true
    style: exclude_zero

  NestingDepth:
    enabled: true
    max_depth: 5

  EmptyLineBetweenBlocks:
    enabled: false
    ignore_single_line_blocks: true

  QualifyingElement:
    allow_element_with_attribute: true
